### ISSUE TITLE
audacity plugin

### ISSUE THREAD

**Issue by marado** [endolith/waveform-analyzer#5]
It would be great to have this turned into an audacity plugin

**Comment by endolith** [comment]
I agree.  Let me know when you've written one!  :D

I actually started making one here, but the Nyquist language is headache-inducing: https://gist.github.com/endolith/514077

**Comment by marado** [comment]
Yeah, I actually saw this github project thanks to that gist ;-)

**Comment by endolith** [comment]
anyway, nyquist is a completely different language, and I don't want to write it, so I'm going to close this.  anyone is welcome to use this code as inspiration for a nyquist version, of course.
